server {
        listen 443 ssl;
        server_name mb3admin.com;
        ssl_certificate /mnt/user/appdata/ca/fullchain.pem;
        ssl_certificate_key /mnt/user/appdata/ca/privkey.pem;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_prefer_server_ciphers on;

        location = /webdefault/images/logo.jpg{
            alias /usr/syno/share/nginx/logo.jpg;
        }

        location @error_page {
            root /usr/syno/share/nginx;
            rewrite (.*) /error.html break;
        }

        location ^~ /.well-known/acme-challenge{
            root /var/lib/letsencrypt;
            default_type text/plain;
        }


        location / {
            rewrite ^ / redirect;
        }

        location ~ ^/$ {
            rewrite / https://$host:5001/redirect;
        }
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers *;
    add_header Access-Control-Allow-Method *;
    add_header Access-Control-Allow-Credentialstrue ture;
#    add_header Access-Control-Allow-Headers: Content-Type, Range, Accept, X-Emby-Token, X-Application;
#    add_header Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS


location /admin/service/registration/validateDevice {
    default_type application/json;
  return 200 '{"cacheExpirationDays":365,"resultCode":"GOOD","message":"Device Valid (limit not checked)"}';
}
location /admin/service/registration/validate {
    default_type application/json;
  return 200 '{"featId":"","registered":true,"expDate":"2099-01-01","key":""}';
}
location /admin/service/registration/getStatus {
    default_type application/json;
  return 200 '{"planType":"Lifetime","deviceStatus":0,"subscriptions":[]}';
}

}